# Codacy configuration for Press On Ventures financial application

# [https://docs.codacy.com/configuration/](https://docs.codacy.com/configuration/)

engines:
  eslint:
    enabled: true
    configFile: eslint.config.js
  react:
    enabled: true
  security:
    enabled: true
    failOnIssues: true
  metrics:
    enabled: true
    complexity:
      maxFunctionComplexity: 10
      maxFileLength: 300
  duplication:
    threshold: 3
  coverage:
    enabled: true
    coverageMinThreshold: 80
    coverageMinThresholdByBranch:
      main: 85
  csslint:
    enabled: true
  shellcheck:
    enabled: true
  jsonlint:
    enabled: true
  sqllint:
    enabled: true

exclude:
  - node_modules/**
  - dist/**
  - build/**
  - coverage/**
  - '**/*.d.ts'
  - '**/*.log'
  - package-lock.json
  - yarn.lock
  - docs/**
  - tests/**
  - 'observability/**'

# Quality gates
quality:
  coverage:
    threshold: 75            # minimum for feature branches
    thresholdByBranch:
      main: 85               # stricter for production
  securityRating:
    required: "A"
  maintainabilityRating:
    required: "A"
  duplicationThreshold: 5     # maximum allowed duplication (%)

# Pull request integration
pullRequests:
  enabled: true
  comments: true
  commitStatus: true

# Branch-specific settings
overrides:
  - pattern: "release/**"
    engines:
      coverage:
        coverageMinThreshold: 85
      metrics:
        duplication:
          threshold: 2

# Coverage patterns (optional)
patterns:
  coverage:
    - coverage/**/*.json
