groups:
  - name: stage-validation
    rules:
      - alert: StageValidationHighRejectRate
        expr: sum(rate(stage_enforce_rejects_total[5m])) / sum(rate(http_requests_total[5m])) > 0.01
        for: 2m
        labels: { severity: page }
        annotations:
          description: 'Enforce rejects >1% over 5m'
          runbook: '/docs/runbooks/stage-normalization-rollout.md#rollback-procedures'

      - alert: StageUnknownHighInWarn
        expr: (sum(rate(stage_warn_unknown_total[10m])) / sum(rate(http_requests_total[10m]))) > 0.01
        for: 10m
        labels: { severity: ticket }
        annotations:
          description: 'Unknown fraction high in WARN; block ENFORCE'
          runbook: '/docs/runbooks/stage-normalization-rollout.md#week-4-rollout'

      # NEW: Validator latency regression alert (1ms budget)
      - alert: StageValidatorLatencyRegression
        expr: histogram_quantile(0.99, sum by (le) (rate(stage_validation_duration_seconds_bucket[5m]))) > 0.001
        for: 5m
        labels: { severity: ticket }
        annotations:
          description: 'Validator p99 latency >1ms (budget violated)'
          runbook: '/docs/runbooks/stage-normalization-rollout.md#performance'

      # NEW: Redis mode store health alert
      - alert: RedisModeFetchFailing
        expr: rate(stage_mode_redis_errors_total[5m]) > 0.1
        for: 2m
        labels: { severity: warn }
        annotations:
          description: 'Redis GET errors >10%; using cached fallback'
          runbook: '/docs/runbooks/stage-normalization-rollout.md#redis-fallback'

      # NEW: Enforce gate unknown rate high (blocks promotion to ENFORCE)
      - alert: EnforceGateUnknownRateHigh
        expr: (sum(rate(stage_warn_unknown_total[10m])) / sum(rate(http_requests_total[10m]))) > 0.005
        for: 10m
        labels: { severity: page, gate: enforce-promotion }
        annotations:
          description: 'Unknown stage rate >0.5% for 10m - blocks WARN → ENFORCE promotion'
          runbook: '/docs/runbooks/stage-normalization-rollout.md#promotion-gates'
