export type RuntimeSurface = 'make_app' | 'register_routes';
export type AuthBoundary = 'public' | 'global_authenticated' | 'router_local';
export type FundScope = 'none' | 'path' | 'query' | 'body' | 'router_defined';
export type ApiRouteOwner = 'platform' | 'gp-team' | 'analytics' | 'lp-reporting';
export type CommonRouteMountStage = 'core' | 'post_response_metrics';

export interface RouteProbe {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  expectedStatus: number;
  body?: unknown;
  authenticated: boolean;
}

export interface CommonApiRouteManifestEntry {
  id: string;
  sourceModule: string;
  mountPath: string | null;
  mountStage?: 'post_response_metrics';
  authBoundary: AuthBoundary;
  fundScope: FundScope;
  financial: boolean;
  schemaTables: readonly string[];
  owner: ApiRouteOwner;
  probe: RouteProbe;
}

export const COMMON_API_ROUTE_MANIFEST = [
  {
    id: 'auth',
    sourceModule: './routes/auth.js',
    mountPath: null,
    authBoundary: 'router_local',
    fundScope: 'none',
    financial: false,
    schemaTables: ['users', 'user_fund_grants'],
    owner: 'platform',
    probe: { method: 'GET', path: '/api/auth/csrf', expectedStatus: 200, authenticated: false },
  },
  {
    id: 'flags',
    sourceModule: './routes/flags.js',
    mountPath: '/api/flags',
    authBoundary: 'router_local',
    fundScope: 'none',
    financial: false,
    schemaTables: ['flag_changes', 'flags_state'],
    owner: 'platform',
    probe: { method: 'GET', path: '/api/flags/status', expectedStatus: 200, authenticated: false },
  },
  {
    id: 'dual-forecast',
    sourceModule: './routes/dual-forecast.js',
    mountPath: '/api',
    authBoundary: 'router_local',
    fundScope: 'path',
    financial: true,
    schemaTables: [
      'funds',
      'fundconfigs',
      'portfoliocompanies',
      'investments',
      'fund_distributions',
      'investment_rounds',
      'investment_round_model_overrides',
      'valuation_marks',
    ],
    owner: 'analytics',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/dual-forecast',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'dashboard-summary',
    sourceModule: './routes/dashboard-summary.js',
    mountPath: '/api',
    authBoundary: 'global_authenticated',
    fundScope: 'path',
    financial: true,
    schemaTables: ['funds', 'portfoliocompanies', 'fund_metrics'],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/dashboard-summary/abc',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'fund-actuals',
    sourceModule: './routes/fund-actuals.js',
    mountPath: '/api',
    authBoundary: 'router_local',
    fundScope: 'path',
    financial: true,
    schemaTables: [
      'funds',
      'portfoliocompanies',
      'investments',
      'investment_rounds',
      'investment_round_model_overrides',
      'valuation_marks',
    ],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/actuals/facts',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'funds',
    sourceModule: './routes/funds.js',
    mountPath: '/api',
    authBoundary: 'global_authenticated',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: ['funds', 'fundconfigs', 'fund_events'],
    owner: 'gp-team',
    probe: { method: 'GET', path: '/api/funds/abc', expectedStatus: 400, authenticated: true },
  },
  {
    id: 'fund-metrics',
    sourceModule: './routes/fund-metrics.js',
    mountPath: null,
    authBoundary: 'router_local',
    fundScope: 'path',
    financial: true,
    schemaTables: [
      'funds',
      'fundconfigs',
      'portfoliocompanies',
      'investments',
      'fund_distributions',
    ],
    owner: 'analytics',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/metrics',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'investments',
    sourceModule: './routes/investments.js',
    mountPath: '/api',
    authBoundary: 'global_authenticated',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: ['investments', 'investment_rounds'],
    owner: 'gp-team',
    probe: { method: 'GET', path: '/api/investments', expectedStatus: 400, authenticated: true },
  },
  {
    id: 'portfolio-companies',
    sourceModule: './routes/portfolio-companies.js',
    mountPath: '/api',
    authBoundary: 'global_authenticated',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: ['portfoliocompanies', 'fund_events', 'fund_snapshots'],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/portfolio-companies',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'portfolio-overview',
    sourceModule: './routes/portfolio-overview.js',
    mountPath: '/api',
    authBoundary: 'global_authenticated',
    fundScope: 'query',
    financial: true,
    schemaTables: ['funds', 'portfoliocompanies', 'fund_events', 'fund_snapshots'],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/portfolio-overview',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'portfolio-lots',
    sourceModule: './routes/portfolio/lots.js',
    mountPath: '/api',
    authBoundary: 'global_authenticated',
    fundScope: 'path',
    financial: true,
    schemaTables: ['investments', 'investment_lots'],
    owner: 'gp-team',
    probe: {
      method: 'POST',
      path: '/api/funds/1/portfolio/lots',
      expectedStatus: 400,
      body: {},
      authenticated: true,
    },
  },
  {
    id: 'performance-api',
    sourceModule: './routes/performance-api.js',
    mountPath: null,
    mountStage: 'post_response_metrics',
    authBoundary: 'router_local',
    fundScope: 'path',
    financial: true,
    schemaTables: [
      'fund_metrics',
      'pacing_history',
      'funds',
      'portfoliocompanies',
      'fund_distributions',
    ],
    owner: 'analytics',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/performance/metrics',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'variance',
    sourceModule: './routes/variance.js',
    mountPath: '/',
    mountStage: 'post_response_metrics',
    authBoundary: 'global_authenticated',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: [
      'fund_baselines',
      'fund_metrics',
      'portfoliocompanies',
      'investments',
      'fund_snapshots',
      'calc_runs',
      'users',
      'variance_reports',
      'alert_rules',
      'alert_evaluation_executions',
      'performance_alerts',
    ],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/variance-dashboard',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'fund-config',
    sourceModule: './routes/fund-config.js',
    mountPath: null,
    mountStage: 'post_response_metrics',
    authBoundary: 'global_authenticated',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: ['funds', 'fundconfigs', 'fund_events', 'fund_snapshots'],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/results',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'allocations',
    sourceModule: './routes/allocations.js',
    mountPath: '/api',
    authBoundary: 'global_authenticated',
    fundScope: 'path',
    financial: true,
    schemaTables: ['funds', 'portfoliocompanies', 'fund_events'],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/companies',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'allocation-scenarios',
    sourceModule: './routes/allocation-scenarios.js',
    mountPath: '/api',
    authBoundary: 'global_authenticated',
    fundScope: 'path',
    financial: true,
    schemaTables: [
      'funds',
      'portfoliocompanies',
      'users',
      'allocation_scenarios',
      'allocation_scenario_items',
      'allocation_scenario_events',
      'allocation_scenario_ic_decisions',
      'fund_events',
    ],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/allocation-scenarios',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'planning-fmv-overrides',
    sourceModule: './routes/planning-fmv-overrides.js',
    mountPath: '/api',
    authBoundary: 'router_local',
    fundScope: 'path',
    financial: true,
    schemaTables: ['planning_fmv_override_requests', 'valuation_marks', 'portfoliocompanies'],
    owner: 'lp-reporting',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/planning/fmv-overrides/latest',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'fund-scenario-sets',
    sourceModule: './routes/fund-scenario-sets.js',
    mountPath: '/api',
    authBoundary: 'router_local',
    fundScope: 'path',
    financial: true,
    schemaTables: [
      'funds',
      'fundconfigs',
      'fund_scenario_sets',
      'fund_scenario_variants',
      'fund_scenario_set_events',
      'fund_scenario_calculation_runs',
      'fund_snapshots',
      'investments',
      'portfoliocompanies',
    ],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/scenario-sets',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'fund-moic',
    sourceModule: './routes/fund-moic.js',
    mountPath: '/api',
    authBoundary: 'router_local',
    fundScope: 'path',
    financial: true,
    schemaTables: [
      'funds',
      'portfoliocompanies',
      'investments',
      'investment_rounds',
      'investment_round_model_overrides',
      'valuation_marks',
      'reconciliation_runs',
      'fund_moic_input_update_requests',
      'fund_events',
      'fund_calculation_modes',
      'fund_calculation_mode_requests',
    ],
    owner: 'analytics',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/moic/rankings',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'timeline',
    sourceModule: './routes/timeline.js',
    mountPath: '/api/timeline',
    mountStage: 'post_response_metrics',
    authBoundary: 'global_authenticated',
    fundScope: 'path',
    financial: true,
    schemaTables: ['funds', 'fund_events', 'fund_snapshots'],
    owner: 'gp-team',
    probe: { method: 'GET', path: '/api/timeline/abc', expectedStatus: 400, authenticated: true },
  },
  {
    id: 'shares',
    sourceModule: './routes/shares.js',
    mountPath: '/api/shares',
    mountStage: 'post_response_metrics',
    authBoundary: 'router_local',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: [
      'shares',
      'share_snapshots',
      'share_analytics',
      'funds',
      'portfoliocompanies',
      'fund_metrics',
    ],
    owner: 'lp-reporting',
    probe: { method: 'GET', path: '/api/shares', expectedStatus: 400, authenticated: true },
  },
  {
    id: 'public-shares',
    sourceModule: './routes/shares.js',
    mountPath: '/api/public/shares',
    mountStage: 'post_response_metrics',
    authBoundary: 'public',
    fundScope: 'none',
    financial: true,
    schemaTables: ['shares', 'share_snapshots', 'share_analytics'],
    owner: 'lp-reporting',
    probe: {
      method: 'POST',
      path: '/api/public/shares/probe/verify',
      expectedStatus: 400,
      body: {},
      authenticated: false,
    },
  },
  {
    id: 'capital-allocation',
    sourceModule: './routes/capital-allocation.js',
    mountPath: '/api/capital-allocation',
    authBoundary: 'global_authenticated',
    fundScope: 'none',
    financial: true,
    schemaTables: [],
    owner: 'analytics',
    probe: {
      method: 'POST',
      path: '/api/capital-allocation/calculate',
      expectedStatus: 400,
      body: {},
      authenticated: true,
    },
  },
  {
    id: 'liquidity',
    sourceModule: './routes/liquidity.js',
    mountPath: '/api/liquidity',
    authBoundary: 'global_authenticated',
    fundScope: 'none',
    financial: true,
    schemaTables: [],
    owner: 'gp-team',
    probe: {
      method: 'POST',
      path: '/api/liquidity/analyze',
      expectedStatus: 500,
      body: {},
      authenticated: true,
    },
  },
  {
    id: 'graduation',
    sourceModule: './routes/graduation.js',
    mountPath: '/api/graduation',
    authBoundary: 'global_authenticated',
    fundScope: 'none',
    financial: true,
    schemaTables: [],
    owner: 'analytics',
    probe: {
      method: 'GET',
      path: '/api/graduation/defaults',
      expectedStatus: 200,
      authenticated: true,
    },
  },
  {
    id: 'reallocation',
    sourceModule: './routes/reallocation.js',
    mountPath: null,
    authBoundary: 'global_authenticated',
    fundScope: 'path',
    financial: true,
    schemaTables: ['funds', 'portfoliocompanies', 'reallocation_audit'],
    owner: 'gp-team',
    probe: {
      method: 'POST',
      path: '/api/funds/abc/reallocation/preview',
      expectedStatus: 400,
      body: {},
      authenticated: true,
    },
  },
  {
    id: 'cash-flow-events',
    sourceModule: './routes/cash-flow-events.js',
    mountPath: null,
    authBoundary: 'global_authenticated',
    fundScope: 'path',
    financial: true,
    schemaTables: ['cash_flow_events', 'funds'],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/cash-flow-events',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'operating-object-tasks',
    sourceModule: './routes/operating-object-tasks.js',
    mountPath: null,
    authBoundary: 'global_authenticated',
    fundScope: 'path',
    financial: true,
    schemaTables: ['tasks', 'funds'],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/tasks',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'deal-pipeline',
    sourceModule: './routes/deal-pipeline.js',
    mountPath: '/api/deals',
    authBoundary: 'global_authenticated',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: [
      'deal_opportunities',
      'due_diligence_items',
      'pipeline_activities',
      'pipeline_stages',
      'scoring_models',
    ],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/deals/opportunities?cursor=not-a-cursor',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'cohort-analysis',
    sourceModule: './routes/cohort-analysis.js',
    mountPath: '/api/cohorts',
    authBoundary: 'router_local',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: [
      'cohort_definitions',
      'portfoliocompanies',
      'investments',
      'sector_taxonomy',
      'sector_mappings',
      'company_overrides',
      'investment_overrides',
      'investment_lots',
    ],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/cohorts/unmapped?fundId=abc',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'sensitivity',
    sourceModule: './routes/sensitivity.js',
    mountPath: '/api',
    authBoundary: 'global_authenticated',
    fundScope: 'path',
    financial: true,
    schemaTables: ['sensitivity_runs', 'fundconfigs'],
    owner: 'gp-team',
    probe: {
      method: 'GET',
      path: '/api/funds/abc/sensitivity/runs',
      expectedStatus: 400,
      authenticated: true,
    },
  },
  {
    id: 'lp-api',
    sourceModule: './routes/lp-api.js',
    mountPath: null,
    mountStage: 'post_response_metrics',
    authBoundary: 'router_local',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: [
      'limited_partners',
      'lp_fund_commitments',
      'capital_activities',
      'lp_capital_accounts',
      'lp_performance_snapshots',
      'portfoliocompanies',
      'investments',
      'lp_reports',
      'funds',
      'lp_audit_log',
    ],
    owner: 'lp-reporting',
    probe: { method: 'GET', path: '/api/lp/profile', expectedStatus: 403, authenticated: true },
  },
  {
    id: 'lp-capital-calls',
    sourceModule: './routes/lp-capital-calls.js',
    mountPath: null,
    mountStage: 'post_response_metrics',
    authBoundary: 'router_local',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: ['lp_capital_calls', 'lp_payment_submissions', 'funds', 'lp_audit_log'],
    owner: 'lp-reporting',
    probe: {
      method: 'GET',
      path: '/api/lp/capital-calls',
      expectedStatus: 403,
      authenticated: true,
    },
  },
  {
    id: 'lp-distributions',
    sourceModule: './routes/lp-distributions.js',
    mountPath: null,
    mountStage: 'post_response_metrics',
    authBoundary: 'router_local',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: ['lp_distribution_details', 'funds', 'lp_audit_log'],
    owner: 'lp-reporting',
    probe: {
      method: 'GET',
      path: '/api/lp/distributions',
      expectedStatus: 403,
      authenticated: true,
    },
  },
  {
    id: 'lp-documents',
    sourceModule: './routes/lp-documents.js',
    mountPath: '/api/lp',
    mountStage: 'post_response_metrics',
    authBoundary: 'router_local',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: ['lp_documents', 'funds', 'lp_audit_log'],
    owner: 'lp-reporting',
    probe: {
      method: 'GET',
      path: '/api/lp/documents',
      expectedStatus: 403,
      authenticated: true,
    },
  },
  {
    id: 'lp-notifications',
    sourceModule: './routes/lp-notifications.js',
    mountPath: '/api/lp',
    mountStage: 'post_response_metrics',
    authBoundary: 'router_local',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: ['lp_notifications', 'lp_notification_preferences', 'lp_audit_log'],
    owner: 'lp-reporting',
    probe: {
      method: 'GET',
      path: '/api/lp/notifications',
      expectedStatus: 403,
      authenticated: true,
    },
  },
  {
    id: 'lp-reporting-imports',
    sourceModule: './routes/lp-reporting/imports.js',
    mountPath: null,
    mountStage: 'post_response_metrics',
    authBoundary: 'router_local',
    fundScope: 'path',
    financial: true,
    schemaTables: [
      'cash_flow_events',
      'valuation_marks',
      'vehicles',
      'portfoliocompanies',
      'users',
      'lp_fund_commitments',
    ],
    owner: 'lp-reporting',
    probe: {
      method: 'POST',
      path: '/api/funds/abc/imports/ledger/dry-run',
      expectedStatus: 400,
      body: {},
      authenticated: true,
    },
  },
  {
    id: 'lp-reporting-metric-runs',
    sourceModule: './routes/lp-reporting/metric-runs.js',
    mountPath: null,
    mountStage: 'post_response_metrics',
    authBoundary: 'router_local',
    fundScope: 'path',
    financial: true,
    schemaTables: [
      'cash_flow_events',
      'valuation_marks',
      'lp_metric_runs',
      'evidence_records',
      'narrative_runs',
      'lp_report_packages',
      'lp_report_package_exports',
      'funds',
      'users',
    ],
    owner: 'lp-reporting',
    probe: {
      method: 'POST',
      path: '/api/funds/abc/metric-runs/dry-run',
      expectedStatus: 400,
      body: {},
      authenticated: true,
    },
  },
  {
    id: 'backtesting',
    sourceModule: './routes/backtesting.js',
    mountPath: '/api/backtesting',
    authBoundary: 'router_local',
    fundScope: 'router_defined',
    financial: true,
    schemaTables: [
      'backtest_results',
      'fund_baselines',
      'variance_reports',
      'fund_state_snapshots',
    ],
    owner: 'analytics',
    probe: {
      method: 'POST',
      path: '/api/backtesting/run',
      expectedStatus: 400,
      body: {},
      authenticated: true,
    },
  },
] as const satisfies readonly CommonApiRouteManifestEntry[];

function assertUniqueManifestIds(entries: readonly CommonApiRouteManifestEntry[]): void {
  const seen = new Set<string>();

  for (const entry of entries) {
    if (seen.has(entry.id)) {
      throw new Error(`Duplicate common API route ID detected: ${entry.id}`);
    }
    seen.add(entry.id);
  }
}

assertUniqueManifestIds(COMMON_API_ROUTE_MANIFEST);

export type CommonApiRouteId = (typeof COMMON_API_ROUTE_MANIFEST)[number]['id'];

export function getCommonRouteMountStage(
  entry: CommonApiRouteManifestEntry
): CommonRouteMountStage {
  return entry.mountStage ?? 'core';
}
