global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'ai-agents'
    static_configs:
      - targets: ['host.docker.internal:3000']  # AI tools metrics endpoint
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'povc-app'
    static_configs:
      - targets: ['host.docker.internal:5000']  # Main application
    metrics_path: '/metrics'
    scrape_interval: 30s