global:
  slack_api_url: '${SLACK_WEBHOOK_URL}'  # Set via environment variable

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
    - match:
        severity: warning
      receiver: 'slack-warning'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'

  - name: 'slack-critical'
    slack_configs:
      - channel: '#ai-agents-alerts'
        color: 'danger'
        title: '🚨 CRITICAL ALERT'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'
        fields:
          - title: 'Alert'
            value: '{{ .GroupLabels.alertname }}'
            short: true
          - title: 'Severity'
            value: '{{ .CommonLabels.severity }}'
            short: true

  - name: 'slack-warning'
    slack_configs:
      - channel: '#ai-agents-alerts'
        color: 'warning'
        title: '⚠️ Warning Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'
        fields:
          - title: 'Alert'
            value: '{{ .GroupLabels.alertname }}'
            short: true
          - title: 'Severity'
            value: '{{ .CommonLabels.severity }}'
            short: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']