import type { ReserveCompanyInput } from '@shared/types';
import { ReserveEngine } from '@shared/core/reserves/ReserveEngine';
import type {
  CreateFundScenarioSetV1,
  CreateReserveOptimizationScenarioSetV1,
  FundScenarioSetDetailV1,
} from '@shared/contracts/fund-scenario-sets-v1.contract';
import { transaction } from '../db/pg-circuit.js';
import { buildReservePortfolioInputForClient } from './reserve-input-builder.js';
import { createFundScenarioSet } from './fund-scenario-set-create-service.js';
import {
  createHttpError,
  verifyFundExists,
  type FundScenarioMutationActor,
} from './fund-scenario-set-service.js';

const DEFAULT_SCENARIO_DESCRIPTION =
  'Generated from current reserve engine recommendations for ADR-022 scenario analysis.';
const DEFAULT_VARIANT_NAME = 'Recommended follow-on allocation';
const DEFAULT_VARIANT_DESCRIPTION =
  'Reserve allocation generated by the reserve optimization workflow.';
const IDEMPOTENCY_KEY_NAME_SUFFIX_LENGTH = 8;
const MAX_ALLOCATION_REASON_LENGTH = 1000;

export function assertOptimizableReservePortfolio(portfolio: ReserveCompanyInput[]): void {
  if (portfolio.length > 0) {
    return;
  }

  throw createHttpError(409, 'Reserve optimization requires portfolio companies', {
    code: 'reserve_optimization_no_portfolio',
  });
}

function defaultScenarioName(generatedAt: Date, idempotencyKey?: string | null): string {
  if (idempotencyKey) {
    return `Optimized reserve plan ${idempotencyKey.slice(0, IDEMPOTENCY_KEY_NAME_SUFFIX_LENGTH)}`;
  }

  return `Optimized reserve plan ${generatedAt.toISOString()}`;
}

function toCents(value: number): number {
  return Math.max(0, Math.round(value * 100));
}

function allocationReason(rationale: string): string {
  return `Optimized reserve recommendation: ${rationale}`.slice(0, MAX_ALLOCATION_REASON_LENGTH);
}

export function buildReserveOptimizationScenarioSetInput(input: {
  fundId: number;
  portfolio: ReserveCompanyInput[];
  request: CreateReserveOptimizationScenarioSetV1;
  generatedAt?: Date;
  idempotencyKey?: string | null;
}): CreateFundScenarioSetV1 {
  assertOptimizableReservePortfolio(input.portfolio);

  const allocations = ReserveEngine(input.portfolio);
  const generatedAt = input.generatedAt ?? new Date();

  return {
    name: input.request.name ?? defaultScenarioName(generatedAt, input.idempotencyKey),
    description:
      input.request.description === undefined
        ? DEFAULT_SCENARIO_DESCRIPTION
        : input.request.description,
    variants: [
      {
        name: input.request.variantName ?? DEFAULT_VARIANT_NAME,
        description: DEFAULT_VARIANT_DESCRIPTION,
        override: {
          overrideType: 'reserve_allocation',
          payload: {
            allocationVersion: 1,
            items: allocations.map((allocation, index) => {
              const company = input.portfolio[index];
              if (company == null) {
                throw new Error(`Missing reserve portfolio company at index ${index}`);
              }

              return {
                companyId: company.id,
                plannedReservesCents: toCents(allocation.allocation),
                maxAllocationCents: null,
                allocationReason: allocationReason(allocation.rationale),
              };
            }),
          },
        },
      },
    ],
  };
}

export async function createReserveOptimizationScenarioSet(
  fundId: number,
  request: CreateReserveOptimizationScenarioSetV1,
  actor: FundScenarioMutationActor,
  options: { idempotencyKey?: string | null } = {}
): Promise<FundScenarioSetDetailV1> {
  const portfolio = await buildReservePortfolioInputForClientForFund(fundId);
  const scenarioSetInput = buildReserveOptimizationScenarioSetInput({
    fundId,
    portfolio,
    request,
    idempotencyKey: options.idempotencyKey ?? null,
  });

  return createFundScenarioSet(fundId, scenarioSetInput, actor, options);
}

async function buildReservePortfolioInputForClientForFund(
  fundId: number
): Promise<ReserveCompanyInput[]> {
  return transaction(async (client) => {
    await verifyFundExists(client, fundId);
    return buildReservePortfolioInputForClient(client, fundId);
  });
}
