name: "Auto-add Migration Issues to Project"

on:
  issues:
    # Fire when an issue is opened or labeled
    types: [opened, labeled]

jobs:
  add_to_project:
    # Only run if the issue has one of these labels
    # Only run if the issue has one of the specified labels.
    # This condition correctly handles both 'opened' and 'labeled' events.
    if: |
      contains(
        github.event.issue.labels.*.name,
        'migration'
      ) || contains(
        github.event.issue.labels.*.name,
        'async-iteration'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Add to Project
        # This action is deprecated but is one of the few that supports setting a column on classic projects.
        # For newer projects (Projects V2), you would need to use the GitHub API via `gh` or another action.
        # It is recommended to migrate to a modern solution in the future.
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/nikhillinit/projects/2
          column: Todo
        env:
          # A personal access token with 'project' scope is required.
          # Store this in your repository's secrets as 'PROJECTS_PAT'.
          GITHUB_TOKEN: ${{ secrets.PROJECTS_PAT }}