name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'

jobs:
  ai-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full history for proper diff

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          cd ai-utils
          pip install -r requirements.txt

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.ts
            **/*.tsx
            **/*.js
            **/*.jsx
          separator: ','

      - name: Run AI code review
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ai-utils
          python scripts/github_pr_review.py \
            --pr-number ${{ github.event.pull_request.number }} \
            --changed-files "${{ steps.changed-files.outputs.all_changed_files }}" \
            --repo ${{ github.repository }}

      - name: Comment on PR
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const reviewPath = 'ai-utils/review_output.md';

            if (!fs.existsSync(reviewPath)) {
              console.log('No review output found');
              return;
            }

            const review = fs.readFileSync(reviewPath, 'utf8');

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🤖 AI Code Review\n\n${review}\n\n---\n*Powered by Claude Sonnet 4.5 with Memory & Context Management*`
            });

      - name: Upload review artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-review-results
          path: ai-utils/review_output.md
          retention-days: 30
