name: calc-parity
on: [pull_request]

concurrency:
  group: parity-${{ github.ref }}
  cancel-in-progress: true

jobs:
  parity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          # Uses your pinned Node via .nvmrc if present
          node-version-file: '.nvmrc'
          cache: npm
      - name: Install
        run: npm ci
      - name: Run parity tests (no server required)
        run: npx vitest run --config vitest.parity.config.ts --reporter=default
      - name: Upload parity artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: parity-report
          path: tests/parity
          retention-days: 30
