name: Check (typecheck + core tests)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: check-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.1'   # avoids EBADENGINE with rest-express@1.3.2
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Core unit tests (Settings-first scope)
        run: npx vitest run --config vitest.core.config.ts --reporter=default

      # Optional: uncomment to verify prod build can compile
      # - name: Build
      #   run: npm run build

      # Optional: upload coverage if configured
      # - name: Upload coverage
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage
      #     path: coverage
      #     retention-days: 7
