name: ci-breaker
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 20
      - run: npm ci || npm i
      - run: npm run -s lint || true
      - run: npm test --workspaces --if-present -- --ci
      - name: List bundle files (if present)
        run: ls -R
