name: CI Hygiene
on: [push]

jobs:
  fast-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Smoke test
        run: |
          npm ci --ignore-scripts
          npm test -- --run --reporter=dot tests/smoke.test.ts

      - name: Policy check – ban Slack deps
        run: |
          if grep -R "@slack" . \
               --exclude-dir=node_modules \
               --exclude-dir=tests \
               --exclude-dir=.github \
               --exclude-dir=shared; then
            echo "::error::Slack dependency found – blocked."
            exit 1
          fi
          echo "✅  No Slack packages found."

      - name: E‑tag monotonicity
        if: >-
          ${{ github.event.head_commit.modified &&
              ( contains(join(github.event.head_commit.modified, ','), 'workers/') ||
                contains(join(github.event.head_commit.modified, ','), 'claude_code') ) }}
        run: |
          PATH_CHANGED=$(echo "${{ github.event.head_commit.modified[0] }}")
          LAST_ETAG=$(tail -1 .async-migration-log | cut -d'|' -f1 | xargs)
          NEW_ETAG=$(./scripts/generate-etag.sh "$PATH_CHANGED")
          if [[ "$NEW_ETAG" <= "$LAST_ETAG" ]]; then
            echo "::error::E‑tag must be monotonic (last=$LAST_ETAG, new=$NEW_ETAG)."
            exit 1
          fi
          echo "✅  E‑tag monotonic."
