name: CI (memory mode)

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: {}

jobs:
  memory-mode:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: '22.16.0'
          cache: 'npm'

      - name: Install
        run: npm ci --legacy-peer-deps

      - name: Type check
        run: npm run check

      - name: Unit/Integration (memory mode)
        env:
          REDIS_URL: memory://
          SIM_SEED: 12345
        run: npm run test:ci

      - name: Flaky Tests (non-blocking)
        if: always()
        continue-on-error: true
        env:
          REDIS_URL: memory://
          SIM_SEED: 12345
        run: npx vitest run --grep "@flaky" --reporter=dot

      - name: Verify no Redis usage in logs
        run: npm run verify:no-redis --if-present