name: CI (memory mode)

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: {}

jobs:
  memory-mode:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
          cache: 'npm'

      - name: Install
        run: npm ci --legacy-peer-deps

      - name: Type check
        run: npm run check

      - name: Unit/Integration (memory mode)
        env:
          REDIS_URL: memory://
        run: npm test --if-present

      - name: Verify no Redis usage in logs
        run: npm run verify:no-redis --if-present