name: CI – Reserves v1.1

on:
  pull_request:
    paths:
      - 'client/src/lib/reserves-v11.ts'
      - 'client/src/lib/quarter-time.ts'
      - 'client/src/adapters/reserves-adapter.ts'
      - 'client/src/schemas/reserves-schema.ts'
      - 'client/src/components/wizard/ReserveStep.tsx'
      - 'client/src/components/reserves/ReservesTable.tsx'
      - 'shared/lib/reserves-v11.ts'
      - 'shared/schemas/reserves-schemas.ts'
      - 'shared/types/reserves-v11.ts'
      - 'tests/unit/reserves-v11.test.ts'
      - 'tests/integration/reserves-integration.test.ts'
      - 'tests/perf/reserves-budget.mjs'
      - '.github/workflows/ci-reserves-v11.yml'
      - '.github/workflows/reusable-ci-core.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.ts'
  push:
    branches: [main, feat/reserves-v11]
  workflow_dispatch:

concurrency:
  group: ci-reserves-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  NODE_VERSION_FILE: .nvmrc

jobs:
  call-core-ci:
    name: Core CI
    uses: ./.github/workflows/reusable-ci-core.yml
    permissions:
      contents: read
      issues: write
      pull-requests: write
    with:
      run-unit-tests: true
      unit-test-path: tests/unit/reserves-v11.test.ts
      run-integration-tests: true
      integration-test-path: tests/integration/reserves-integration.test.ts
      run-bundle-analysis: true
      # Uncomment to enable visual regression tests when PR has 'visual-test' label
      # run-visual-regression: ${{ contains(github.event.pull_request.labels.*.name, 'visual-test') }}
      # visual-regression-path: tests/e2e/reserves-demo.spec.ts
