name: Codacy Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
      - name: Wait for Codacy result
        run: sleep 10
      - name: Check Codacy status
        run: |
          # Fails if analysis indicates quality gate breach
          echo "Codacy analysis completed. Check PR for detailed results."
