name: Linux Build Validation (Manual)

on:
  workflow_dispatch: # Manual trigger only
    inputs:
      reason:
        description: 'Reason for running validation'
        required: false
        default: 'Phase -1 Linux build compatibility test'

jobs:
  validate-linux-build:
    name: Validate Build on Linux
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: feat/typescript-baseline-system

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.x'
          cache: 'npm'

      - name: Display environment info
        run: |
          echo "=== Environment Information ==="
          echo "CI=$CI"
          echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"
          echo "Node.js version: $(node -v)"
          echo "npm version: $(npm -v)"
          echo "OS: $(uname -a)"
          echo "Validation reason: ${{ github.event.inputs.reason }}"
          echo ""

      - name: Install dependencies
        run: |
          echo "=== Installing dependencies with CI=true ==="
          npm ci
        env:
          CI: true

      - name: Verify sidecar disabled
        run: |
          echo "=== Verifying sidecar auto-disable behavior ==="
          if [ -L "node_modules/vite" ]; then
            echo "❌ ERROR: Sidecar still active (symlink detected)"
            ls -la node_modules/vite
            exit 1
          else
            echo "✅ Sidecar correctly disabled in CI environment"
            ls -ld node_modules/vite
          fi

      - name: TypeScript type check
        run: |
          echo "=== Running TypeScript type check ==="
          npm run typecheck

      - name: Production build
        run: |
          echo "=== Building for production ==="
          npm run build

      - name: Run test suite
        run: |
          echo "=== Running test suite ==="
          npm test

      - name: Report success
        if: success()
        run: |
          echo ""
          echo "╔════════════════════════════════════════════════╗"
          echo "║  ✅ Linux Build Validation PASSED             ║"
          echo "╚════════════════════════════════════════════════╝"
          echo ""
          echo "Results:"
          echo "  • TypeScript check: ✅ PASSED"
          echo "  • Production build: ✅ PASSED"
          echo "  • Test suite:       ✅ PASSED"
          echo "  • Sidecar behavior: ✅ VERIFIED (disabled in CI)"
          echo ""
          echo "Conclusion: Linux build compatibility confirmed"
          echo "Ready for Phase 0 integration"

      - name: Report failure
        if: failure()
        run: |
          echo ""
          echo "╔════════════════════════════════════════════════╗"
          echo "║  ❌ Linux Build Validation FAILED             ║"
          echo "╚════════════════════════════════════════════════╝"
          echo ""
          echo "Investigation required - check logs above"
          echo "Timeline impact: +1-2 days for debugging"
