name: perf-smoke
on: [pull_request]

jobs:
  k6:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install
        run: npm ci

      - name: Setup database
        run: npm run db:push
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test

      # Start your server exactly as you run it in CI today.
      # We wait for health at :3001 per your current setup.
      - name: Start server
        run: |
          npx tsx server/index.ts &
          npx wait-on http://localhost:3001/api/health --timeout 60000
        env:
          NODE_ENV: test
          PORT: 3001
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
          REDIS_URL: memory://
          # Disable OpenTelemetry in CI to avoid initialization issues
          OTEL_SDK_DISABLED: true

      - name: Run k6 smoke test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/perf/smoke.js
        env:
          BASE_URL: http://localhost:3001
