name: perf-smoke
on: [pull_request]

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install
        run: npm ci

      # Start your server exactly as you run it in CI today.
      # We wait for health at :3001 per your current setup.
      - name: Start server
        run: |
          node server/index.js &
          npx wait-on http://localhost:3001/api/health --timeout 60000
        env:
          NODE_ENV: test
          # If needed, add TEST_DATABASE_URL to repo secrets.
          # DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}

      - name: Run k6 smoke test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/perf/smoke.js
        env:
          BASE_URL: http://localhost:3001
