name: Post-Merge Validation

on:
  push:
    branches: [ main ]

jobs:
  post-merge-smoke:
    runs-on: ubuntu-latest
    name: Post-merge smoke test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Enable git range-diff if needed
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
      - name: Migration E2E (fast fail)
        run: |
          npx playwright install --with-deps
          E2E_WIZARD=1 npx playwright test tests/e2e/localstorage-migration.spec.ts --reporter=dot
      - name: Core functionality smoke
        run: |
          npx vitest run client/src/core/reserves --reporter=dot --run
          npx vitest run client/src/stores/useFundStore --reporter=dot --run
      - name: Build validation
        run: npm run build
      
  notify-on-failure:
    runs-on: ubuntu-latest
    needs: post-merge-smoke
    if: failure()
    steps:
      - name: Create issue on failure
        uses: actions/github-script@v7
        with:
          script: |
            const commit = context.sha.substring(0, 8);
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 Post-merge validation failed (${commit})`,
              body: `## Post-merge validation failure
              
              **Commit:** ${context.sha}
              **Workflow:** [View run](${runUrl})
              **Branch:** ${context.ref}
              
              ### Issues detected:
              - Migration E2E or smoke tests failed after merge to main
              - This indicates a potential regression in production
              
              ### Immediate actions:
              1. Review the [failed workflow](${runUrl})
              2. Consider hotfix or rollback if issue is severe
              3. Fix underlying issue in a follow-up PR
              
              ### Auto-rollback:
              If this is a critical failure, you can trigger auto-rollback:
              \`\`\`bash
              # Monitor for 10 minutes with auto-revert enabled
              pwsh scripts/monitor-deployment.ps1 -MinutesToMonitor 10 -ErrorThreshold 1 -AutoRevert
              \`\`\`
              
              *This issue was created automatically by post-merge validation.*`,
              labels: ['production-issue', 'post-merge-failure', 'hotfix']
            });
