name: PR Tests (Main Workspace)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'docs/**'
      - 'scripts/validation/**'
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run check || npm run typecheck || true

      - name: Lint
        run: npm run lint || true

      - name: Unit tests (main workspace)
        id: run_tests
        shell: bash
        run: |
          mkdir -p reports
          # Run with JSON reporter for machine-readable output
          npx vitest -c vitest.config.unit.ts run --reporter=json > reports/vitest-results.json || true
          echo "vitest_exit=$?" >> $GITHUB_OUTPUT
        env:
          CI: true
        continue-on-error: true

      - name: Generate stability report
        if: always()
        run: node scripts/ci/parse-vitest-json.mjs
        env:
          VITEST_JSON: reports/vitest-results.json
        continue-on-error: true

      - name: Upload test reports
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        if: always()
        with:
          name: test-reports-${{ github.run_number }}
          path: |
            reports/**
            coverage/**
          if-no-files-found: ignore
          retention-days: 7

      # Fail the job if tests failed
      - name: Check test results
        if: always()
        shell: bash
        run: |
          if [ "${{ steps.run_tests.outputs.vitest_exit }}" != "0" ] && [ "${{ steps.run_tests.outputs.vitest_exit }}" != "" ]; then
            echo "Unit tests failed with exit code ${{ steps.run_tests.outputs.vitest_exit }}"
            exit 1
          fi
