name: Promote ESLint Rule
on:
  schedule:
    # Run at 10 PM daily - adjust timezone as needed
    - cron: '0 22 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check if promotion needed
        id: check
        run: |
          if grep -q '"warn"' eslint.config.js; then
            echo "needs_promotion=true" >> $GITHUB_OUTPUT
          else
            echo "needs_promotion=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Promote rule to error
        if: steps.check.outputs.needs_promotion == 'true'
        run: |
          sed -i 's/"warn"/"error"/' eslint.config.js
          
      - name: Commit and push
        if: steps.check.outputs.needs_promotion == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add eslint.config.js
          git commit -m "chore(lint): promote async rule to error [automated]"
          git push
