name: Quarantine Tests (Nightly)

on:
  schedule:
    - cron: '23 3 * * *' # 03:23 UTC nightly
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  quarantine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install
        id: install_deps
        run: npm ci
        continue-on-error: true

      - name: Run quarantine tests (JSON)
        id: run_quarantine
        if: steps.install_deps.outcome == 'success'
        shell: bash
        run: |
          mkdir -p reports
          npx vitest -c vitest.config.quarantine.ts run --reporter=json > reports/vitest-quarantine.json || echo "exit_code=$?" >> $GITHUB_OUTPUT
          echo "exit_code=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        with:
          name: vitest-quarantine-reports
          path: reports/**
          if-no-files-found: ignore

      - name: Open issue on failure
        if: failure() || steps.install_deps.outcome == 'failure' || (steps.run_quarantine.outputs.exit_code != '0' && steps.run_quarantine.outputs.exit_code != '')
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            const date = new Date().toISOString().split('T')[0];
            const installStatus = '${{ steps.install_deps.outcome }}';
            const testExitCode = '${{ steps.run_quarantine.outputs.exit_code }}';

            let failureReason = '';
            if (installStatus === 'failure') {
              failureReason = '**Installation failed** - Check workflow logs for npm ci errors';
            } else if (testExitCode && testExitCode !== '0') {
              failureReason = `**Tests failed** - Exit code: ${testExitCode}`;
            } else {
              failureReason = '**Unknown failure** - Check workflow logs';
            }

            const body = `
            ## Quarantine Tests Failed - ${date}

            The nightly quarantine test run has failed.

            - **Failure reason:** ${failureReason}
            - **Installation status:** ${installStatus}
            - **Test exit code:** ${testExitCode || 'N/A'}
            - **Workflow run:** [View run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - **Artifacts:** vitest-quarantine-reports

            ### Next Steps
            1. Download the test artifacts to see detailed failure information
            2. If installation failed, check for dependency or script issues
            3. If tests failed, fix the failing tests or adjust timeouts if needed
            4. When tests pass 10/10 times, graduate them back to the main suite

            _This issue was automatically created by the nightly quarantine runner._
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[Test] Quarantine tests failed - ${date}`,
              body,
              labels: ['test', 'automated']
            });
