name: Slack Regression Guard
on: [pull_request, push]
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      fail-fast: true
      matrix:
        shard: [1, 2]
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Check for Slack references (shard ${{ matrix.shard }})
        run: |
          # Split files across shards for faster execution
          files=$(git ls-files | head -n $((${{ matrix.shard }} * 500)))
          
          if git grep -n -i slack -- $files \
            ':!.github/workflows/slack-regression-guard.yml' \
            ':!.github/workflows/bmad-weekly.yml' \
            ':!.github/workflows/deploy-ga.yml' \
            ':!.github/workflows/synthetic.yml' \
            ':!.env.example' \
            ':!docs/legacy/*' \
            ':!.migration/*' \
            ':!.config/*' \
            ':!*.md' \
            ':!tatus' \
            ':!docs/*' \
            ':!observability/*' \
            ':!packages/*/README.md' \
            ':!repo/*' \
            ':!scripts/apply-hotfixes.sh' \
            ':!scripts/update-branch-protection.js' \
            ':!.github/dependabot.yml' \
            ':!.github/workflows/ci-hygiene.yml' \
            ':!.github/workflows/maintenance.yml' \
            ':!.github/workflows/migration-orchestrator.yml' \
            ':!launch-script.sh' \
            ':!shared/slack.ts' \
            ':!services/SlackService.ts' \
            ':!eslint.config.js' \
            ':!**/*slack*.ts' \
            ':!**/*Slack*.ts'; then
            echo '❌  Slack reference found in shard ${{ matrix.shard }}'; exit 1
          fi
          echo '✅  Shard ${{ matrix.shard }} Slack-free'
