name: Slack Regression Guard
on: [pull_request, push]
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: |
          if git grep -n -i slack -- ':!.github/workflows/slack-regression-guard.yml' ':!docs/legacy/*'; then
            echo '❌  Slack reference found'; exit 1
          fi
          echo '✅  Slack‑free'
