name: Slack Regression Guard
on: [pull_request, push]
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      fail-fast: true
      matrix:
        shard: [1, 2]
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Check for Slack references (shard ${{ matrix.shard }})
        run: |
          # Split files across shards for faster execution
          files=$(git ls-files | head -n $((${{ matrix.shard }} * 500)))
          
          if git grep -n -i slack -- $files ':!.github/workflows/slack-regression-guard.yml' ':!docs/legacy/*' ':!.migration/*'; then
            echo '❌  Slack reference found in shard ${{ matrix.shard }}'; exit 1
          fi
          echo '✅  Shard ${{ matrix.shard }} Slack-free'
