name: synthetics-e2e
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  schedule: 
    - cron: '*/10 * * * *'

concurrency:
  group: synthetics-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with: 
          node-version: '22'
          cache: 'npm'
      
      - run: npm ci
      - run: npx playwright install --with-deps
      
      - name: Resolve BASE_URL
        id: base
        shell: bash
        run: |
          # Priority 1: main pushes with SYNTHETIC_URL secret
          if [ "${{ github.event_name }}" = "push" ] && \
             [ "${{ github.ref }}" = "refs/heads/main" ] && \
             [ -n "${{ secrets.SYNTHETIC_URL }}" ]; then
            echo "base=${{ secrets.SYNTHETIC_URL }}" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          # Priority 2: repository variables for PRs
          if [ -n "${{ vars.SYNTHETIC_URL }}" ]; then
            echo "base=${{ vars.SYNTHETIC_URL }}" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          # No URL available -> skip to avoid red CI on forks
          echo "skip=true" >> "$GITHUB_OUTPUT"
      
      - name: Run E2E Wizard Flow
        if: steps.base.outputs.skip != 'true'
        env:
          BASE_URL: ${{ steps.base.outputs.base }}
        shell: bash
        run: |
          set -euxo pipefail
          # Try the 'smoke' project; if not defined, fall back to default.
          npx playwright test tests/synthetics/wizard.e2e.spec.ts --project=smoke --reporter=html,line || \
          npx playwright test tests/synthetics/wizard.e2e.spec.ts --reporter=html,line
      
      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts-${{ github.run_id }}
          path: |
            playwright-report/
            test-results/
          if-no-files-found: ignore
