name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Prevent concurrent runs on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting with built-in cache
      run: npm run lint
    
    - name: Run tests
      run: npm test
    
    - name: Run build
      run: npm run build --if-present

  # Experimental features gated behind feature flag
  experimental:
    runs-on: ubuntu-latest
    if: vars.CI_EXPERIMENTAL == 'true'
    needs: test
    env:
      CI_EXPERIMENTAL: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate ETag artifacts
      run: |
        echo "etag-$(date +%s)" > etag.txt
        echo "Generated ETag: $(cat etag.txt)"
    
    - name: Upload ETag artifact
      uses: actions/upload-artifact@v4
      with:
        name: etag-${{ github.sha }}
        path: etag.txt
        retention-days: 7
