name: validate
on:
  pull_request:
    branches: [ai_main_23984511d18b, main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 20

      - run: npm ci

      - name: Unit/lint/types
        run: npm run test:all

      - name: Build
        run: npm run build

      - name: Demo smoke
        run: |
          npx playwright install --with-deps
          npx playwright test tests/e2e/reserves-demo.smoke.spec.ts
