name: DAST-ZAP-Baseline
on:
  workflow_dispatch: {}
  schedule: [ { cron: '30 3 * * 1' } ]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ secrets.ZAP_BASE_URL }}
          rules_file_name: '.zap/rules.tsv'
          fail_action: true
          cmd_options: '-a'
