import { describe, expect, it } from 'vitest';

import {
  assertOptimizableReservePortfolio,
  buildReserveOptimizationScenarioSetInput,
} from '../../../server/services/fund-scenario-reserve-optimization-workflow-service';

describe('reserve optimization scenario workflow', () => {
  it('builds a reserve-allocation scenario set from existing reserve recommendations', () => {
    const input = buildReserveOptimizationScenarioSetInput({
      fundId: 1,
      portfolio: [
        { id: 101, invested: 500_000, ownership: 0.15, stage: 'Seed', sector: 'SaaS' },
        { id: 102, invested: 1_000_000, ownership: 0.12, stage: 'Series A', sector: 'Fintech' },
      ],
      request: {
        name: 'Optimized reserve plan',
        variantName: 'Recommended follow-on allocation',
      },
      generatedAt: new Date('2026-05-29T10:00:00.000Z'),
    });

    expect(input).toMatchObject({
      name: 'Optimized reserve plan',
      description:
        'Generated from current reserve engine recommendations for ADR-022 scenario analysis.',
      variants: [
        {
          name: 'Recommended follow-on allocation',
          description: 'Reserve allocation generated by the reserve optimization workflow.',
          override: {
            overrideType: 'reserve_allocation',
            payload: {
              allocationVersion: 1,
              items: [
                {
                  companyId: 101,
                  maxAllocationCents: null,
                },
                {
                  companyId: 102,
                  maxAllocationCents: null,
                },
              ],
            },
          },
        },
      ],
    });
    const items = input.variants[0]?.override.payload.items ?? [];
    expect(items).toHaveLength(2);
    expect(items[0]?.plannedReservesCents).toBeGreaterThan(0);
    expect(items[0]?.allocationReason).toMatch(/^Optimized reserve recommendation:/);
    expect(items[1]?.plannedReservesCents).toBeGreaterThan(0);
    expect(items[1]?.allocationReason).toMatch(/^Optimized reserve recommendation:/);
  });

  it('uses an idempotency-safe default name when an idempotency key is present', () => {
    const input = buildReserveOptimizationScenarioSetInput({
      fundId: 1,
      portfolio: [{ id: 101, invested: 500_000, ownership: 0.15, stage: 'Seed', sector: 'SaaS' }],
      request: {},
      generatedAt: new Date('2026-05-29T10:00:00.000Z'),
      idempotencyKey: 'abcdef1234567890',
    });

    expect(input.name).toBe('Optimized reserve plan abcdef12');
  });

  it('rejects empty portfolios before creating scenario sets', () => {
    expect(() => assertOptimizableReservePortfolio([])).toThrow(/portfolio companies/);
  });
});
